version: '2'
linters:
  default: all
  disable:
    - depguard
    - exhaustruct
    - embeddedstructfieldcheck
    - funcorder
    - nlreturn
    - wsl
  exclusions:
    generated: lax
    presets:
      - legacy
      - std-error-handling
formatters:
  enable:
    - gci
    - gofmt
    - gofumpt
    - goimports
