## Example Fog Willow config file.
## The values below are the defaults.
#####################################

# FW_PASSWORD: If a password is set then clients must send it as a setting.
password = ""
# FW_LISTEN_ADDR: IP and UDP port to listen on for UDP packets to write to disk.
listen_addr = ":9000"
# FW_FLUSH_INTERVAL: How old an item must be to flush it to disk.
flush_interval = "16s"
# FW_GROUP_INTERVAL: How often to scan everything for flushable files.
group_interval = "4s"
# FW_OUTPUT_PATH: This is prefixed to whatever comes in over the wire.
output_path  = "/tmp"
# FW_LOG_FILE: This should be a full path, probably /config/fog.log.
log_file = ""
# FW_LOG_FILE_MB: Size of each log file.
log_file_mb = 0
# FW_LOG_FILES: How many logs files to keep around.
log_files = 0
# FW_BUFFER_UDP: This is the UDP socket buffer in bytes.
buffer_udp = 4194304 # 4MB
# FW_BUFFER_PACKET: This is the size of the read buffer per packet.
buffer_packet = 262144 # 256KB
# FW_BUFFER_CHAN: This is the channel buffer between the listeners and processors.
buffer_chan = 32768 # 32 thousand
# FW_LISTENERS: How many UDP socket listener threads to start.
listeners = 1
# FW_PROCESSORS: How many packet processor threads to start.
processors = 1
# FW_WRITERS: How many file system operations may happen in parallel. 2-5 is fine with fast disks.
writers = 1
# FW_BUFFER_FILE_SYS: How many file pointers can be buffered into the file system writer.
buffer_file_sys = 32768 # 32 thousand
# FW_DEBUG: Prints 1 line per packet when enabled.
debug = false

# FW_HTTP_SERVER: Configuration for the HTTP server.
[http_server]
# FW_HTTP_SERVER_LISTEN_ADDR: IP and TCP port to listen on. For API and metrics via HTTP.
listen_addr = ":9000"
# FW_HTTP_SERVER_READ_TIMEOUT: Maximum duration for reading the entire request, including the body.
read_timeout = "10s"
# FW_HTTP_SERVER_READ_HEADER_TIMEOUT: Maximum duration for reading the request header.
read_header_timeout = "2s"
# FW_HTTP_SERVER_WRITE_TIMEOUT: Maximum duration for writing the response to the client.
write_timeout = "10s"
# FW_HTTP_SERVER_IDLE_TIMEOUT: Maximum amount of time to wait for the next request when keep-alives are enabled.
idle_timeout = "120s"
# FW_HTTP_SERVER_MAX_HEADER_BYTES: Maximum number of bytes the server will read parsing the request header's keys and values, including the request line.
max_header_bytes = 65536 # 64KB
# FW_HTTP_SERVER_TLS_CERT_PATH: Path to the TLS certificate file. Provide this to enable HTTPS.
tls_cert_path = ""
# FW_HTTP_SERVER_TLS_KEY_PATH: Path to the TLS private key file for the certificate. Provide this to enable HTTPS.
tls_key_path = ""
