# This is an example of how to override the user to something other than root.
# Install this file to: /etc/systemd/system/fogwillow.service.d/override.conf
# We use this file in production to run fogwillow on a notifiarr worker.
[Service]
User=abc
Group=abc
PermissionsStartOnly=true
ExecStartPre=/bin/chown -R abc: /var/log/fogwillow
